### ISSUE TITLE
#4 - Implement functionality to POST a new activity.

### ISSUE THREAD

**Issue by olikelly00** [SchoolOfCode/bc17-w4d2-project-meng-zhi-dui#4]
As Kenny, a busy front end engineer I need to be able to send a POST request with a JSON request body (new activity) to the API so that I can make a simple form that allows my user to submit new activity.

As Norman, a Tech Lead working across lots of projects I need to be able to depend on conventions like: the response object always containing a key called data or error, or the status code being an accurate indication of the success/failure (and reason) of the request.

Acceptance Criteria:

Given I am a developer who has the Activity API running,
When I make a POST request to “http://localhost:3000/activities” with a request body containing a JSON object (new activity),
Then the API should save the new activity to the activities.json file giving it a unique “id” (UUID) and activity_submitted (time stamp - Date.now()),
Then the the request should succeed, responding with the correct status code and the activity object that I posted as the response body (response.data).
```[tasklist]
### Tasks
- [x] Write a function to add activity giving complete object
- [x] import function to app.js
- [x] write handler functon to handle post request with add activity
- [x] test post request (with hard coded values) with new activity using postman
- [x] modify function to only take activty type & length and add uuid and timestamp
- [x] Make the response body include the new activity object
```
